theme: minima
title: Example Blog
author: Lucas Rodriguez
email: example@nonexistent.com
description: > # this means to ignore newslines until "baseurl:"
This blog only serves as an example and is used for practical purposes.

# social link
github_username: ColdCoder92

show_excerpts: true # set to false to remove excerpts on the homepage
